//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CRUD_DEMO.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_category
    {
        public int pcid { get; set; }
        public string pcname { get; set; }
    }
}
